name: config
command: ipfs config
options:
  - name: json
    type: bool
    description: Parse stringified JSON.
  - name: bool
    type: bool
    description: Set a boolean value.
arguments:
  - name: value
    type: string
    required: false
    description: The value to set the config entry to.
  - name: key
    type: string
    required: true
    description: The key of the config entry (e.g. "Addresses.API").
help:
  tagline: Get and set IPFS config values.
  short: |
    'ipfs config' controls configuration variables. It works like 'git config'.
    The configuration values are stored in a config file inside your IPFS
    repository.
  long: |
    'ipfs config' controls configuration variables. It works
    much like 'git config'. The configuration values are stored in a config
    file inside your IPFS repository.
    
    Examples:
    
    Get the value of the 'datastore.path' key:
    
      $ ipfs config datastore.path
    
    Set the value of the 'datastore.path' key:
    
      $ ipfs config datastore.path ~/.ipfs/datastore
