name: show
command: ipfs config show
help:
  tagline: Outputs the content of the config file.
  short: |
    WARNING: Your private key is stored in the config file, and it will be
    included in the output of this command.
  long: null
